name: Crouch-Jump
main: xyz.kaisershare.crouchjump.Main
version: 1.0.1
api-version: 1.13
description: A customizable plugin that temporarily grants Jump Boost to a player when they crouch.
author: evelon
website: https://kaisershare.xyz
commands:
   crouchjump:
     description: Reloads the crouch-jump plugin's configuration file
     aliases: [crouch-jump, cj]
     permission: crouchjump.cmd
     permission-message: "§cAccess denied."
permissions:
   crouchjump.cmd:
     default: op
     description: "Allows usage of /crouchjump"