name: Crouch-Jump
main: xyz.kaisershare.crouchjump.Main
version: 0.1.3
api-version: 1.13
description: Tries to emulate how the Source engine handles crouch-jumping.
author: KaiserShare.xyz
website: https://kaisershare.xyz
commands:
  crouchjump:
    description: Reloads the crouch-jump plugin's config.
    #usage: /crouchjump
    permission: crouchjump.cmd
    permission-message: "§cAccess denied."
    #usage: "Usage: /crouchjump [reload]"
permissions:
  crouchjump.cmd:
    default: op
    description: Allows use for /crouchjump.